using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using HKLib.hk2018;
using HKLib.Serialization;

namespace HKLib.Modding;

/// <summary>
/// Performs a series of checks on the reconstructed Havok data to ensure its integrity before final serialization.
/// This corresponds to the "Binary Integrity Checker" step of Phase 4.
/// </summary>
public static class BinaryIntegrityChecker
{
    /// <summary>
    /// Validates the integrity of the in-memory Havok object graph and its layout data.
    /// Throws an <see cref="InvalidDataException"/> if any validation rule is violated.
    /// </summary>
    /// <param name="root">The root object of the Havok file.</param>
    /// <param name="packerData">The data generated by the layout pass of the packer.</param>
    /// <param name="masterBoneCount">The expected number of bones ($N$) in the master skeleton.</param>
    public static void Validate(IHavokObject root, PackerData packerData, int masterBoneCount)
    {
        var errors = new List<string>();

        CheckAlignment(packerData, errors);
        CheckPointerTargets(packerData, errors);
        CheckDataConsistency(root, masterBoneCount, errors);

        if (errors.Count > 0)
        {
            throw new InvalidDataException("Binary integrity check failed with the following errors:\n" +
                                           string.Join("\n", errors));
        }
    }

    private static void CheckAlignment(PackerData packerData, List<string> errors)
    {
        foreach (var (obj, address) in packerData.AddressMap)
        {
            if (address % 16 != 0)
            {
                errors.Add(
                    $"[Alignment Error] Object '{obj.GetType().Name}' at address 0x{address:X} is not 16-byte aligned.");
            }
        }
    }

    private static void CheckPointerTargets(PackerData packerData, List<string> errors)
    {
        var validAddresses = new HashSet<long>(packerData.AddressMap.Values);
        foreach (var patch in packerData.Patches)
        {
            // A destination of 0 is a null pointer, which is valid.
            if (patch.DestinationOffset != 0 && !validAddresses.Contains(patch.DestinationOffset))
            {
                errors.Add(
                    $"[Pointer Error] Patch at 0x{patch.SourceOffset:X} points to an invalid address 0x{patch.DestinationOffset:X} which is not the start of any known object.");
            }
        }
    }

    private static void CheckDataConsistency(IHavokObject root, int masterBoneCount, List<string> errors)
    {
        HavokObjectWalker.Walk(root, obj =>
        {
            switch (obj)
            {
                case hkaSkeleton skeleton when skeleton.m_bones.Count != masterBoneCount:
                    errors.Add(
                        $"[Data Mismatch: hkaSkeleton] Expected {masterBoneCount} bones, but found {skeleton.m_bones.Count}.");
                    break;
                case hknpPhysicsSystemData physicsData when physicsData.m_boneIdToBodyIdMap.Count != masterBoneCount:
                    errors.Add(
                        $"[Data Mismatch: hknpPhysicsSystemData] Expected boneIdToBodyIdMap size of {masterBoneCount}, but found {physicsData.m_boneIdToBodyIdMap.Count}.");
                    break;
                case hkaAnimation animation when animation.m_numberOfTransformTracks != masterBoneCount:
                    errors.Add(
                        $"[Data Mismatch: hkaAnimation] Expected numberOfTransformTracks to be {masterBoneCount}, but found {animation.m_numberOfTransformTracks}.");
                    break;
            }
        });
    }
}